# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
# SPDX-FileCopyrightText: Leslie Lazzarino <leslie.lazzarino@tngtech.com>
# SPDX-FileCopyrightText: Benedikt Richter <benedikt.richter@tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn setup
      - run: yarn lint
      - run: yarn test
